### PR TITLE
More updates for latest Zig

### PR DESCRIPTION
**Pull request by xtian**
- Use `@as` for type coercion: https://ziglang.org/documentation/0.7.0/#as
- Use `@typeInfo`: https://ziglang.org/documentation/0.7.0/#typeInfo
- Use `@TypeOf`: https://ziglang.org/documentation/0.7.0/#TypeOf
- Fix `CW_USEDEFAULT`

### CODE REVIEW

**Comment by xtian** [comment]
@GoNZooo The updated version of `CW_USEDEFAULT` compiles but it doesn't actually work. What works in my code is `@as(INT, 0x8000)`. Can you explain what the definition of `CW_USEDEFAULT` is trying to do?

**Comment by GoNZooo** [comment]
> Can you explain what the definition of `CW_USEDEFAULT` is trying to do?

`CW_USEDEFAULT` is just an enum value for `CreateWindow` to use a default value for a given parameter. What you're modifying is automatically generated code that was generated via `translate-c` and copied into the repository, then annotated with link data + modified over time to address compilation errors. There's no purpose to any of the generated code beyond Zig's translation of whatever C-isms are in there.

The only purpose to changing these files should be to either:

a) Match whatever output Zig gives for a given construct nowadays, provided it works (this isn't always the case; Zig has had plenty of regressions in auto-generated code)

b) Fix whatever Zig cannot compile on latest `master`, meaning it deprecated some syntax.

c) Fix things that have always been/ended up wrong because of Zig's translation or modifications made.

A convenient way of renewing translation can be to `@cImport` `windows.h` and compile with `--verbose-cimport` to locate the file it generated and see what it would generate nowadays. If the thing it generates for a certain binding works, that's fine and should be changed. If it's the case that the older generated code doesn't compile anymore and there are no clear ways to just change what constructs it's using a hand-modified version that conforms to whatever it needs to is obviously fine.

As for the exact example of `CW_USEDEFAULT` I can only assume that at some point Zig saw through some MAX_INT value but not enough to see that it's not a pointer or whatever, I don't know.

The value for `CW_USEDEFAULT` is indeed `(int)0x80000000`, so setting it to this wherever applicable would be reasonable.

**Comment by GoNZooo** [comment]
@xtian Are there more changes that should be put in this PR?

**Comment by xtian** [comment]
@GoNZooo Sorry for the delay! I updated `CW_USEDEFAULT` to use the constant value.

I haven't continued to exercise this code so I'm not sure if there are additional changes necessary. I switched to using the [ZWL Windows module](https://github.com/Aransentin/ZWL/blob/58df908da15a55a564d603cccf35624e56cd6372/src/windows.zig) in my project for now.

**Pull request merged**
